on:
  push:
    tags:
    - 'v*'

name: Release CI

jobs:
  build:
    name: Upload release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@master
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Package
        run: mvn -B verify
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/cdoc.*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

